---
- hosts: localhost
  vars:
    ssh_keys:
      - name: "tomatoai"
        src_key: "../.ssh/tomatoai_rsa"
        dest_key: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
        src_pub_key: "../.ssh/tomatoai_rsa.pub"
        dest_pub_key: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
        gist_host: "gist.github.com-tomatoai"
  tasks:

    - include_tasks: tasks/core.yml
      tags:
        - core

    - include_tasks: tasks/ssh.yml
      tags:
        - ssh 

    - include_tasks: tasks/zsh.yml
      tags:
        - zsh

    - include_tasks: tasks/git-config.yml
      tags:
        - git-config

    - include_tasks: tasks/nvm.yml
      tags:
        - nvm 

    - include_tasks: tasks/tomato-frontend.yml
      tags:
        - tomato

    - include_tasks: tasks/tomato-backend.yml
      tags:
        - tomato
        - docker-build

