# =========================== Core Task: System Packages =========================
- name: Ensure system utility packages are installed
  community.general.homebrew:
    name:
      - zsh
      - fzf
      - libpq
      - font-caskaydia-mono-nerd-font
      - pkg-config
      - cairo
      - pango
      - libpng
      - jpeg
      - giflib
      - librsvg
      - docker-compose
    state: present
    update_homebrew: yes
  tags:
    - packages

# =========================== Core Task: Flow Packages =========================
- name: Ensure Flow utility packages are installed
  community.general.homebrew:
    name:
      - tmux
      - neovim
      - fzf
      - ollama
    state: present
    update_homebrew: yes
  tags:
    - packages

# =========================== Core Task: UI Packages =========================
- name: Install desktop applications with Homebrew Cask
  community.general.homebrew_cask:
    name:
      - wezterm
      - docker
      - slack
      - firefox
      - google-chrome
      - dbeaver-community
      - tableplus
      - termius
      - visual-studio-code
    state: present
  tags:
    - packages

# =========================== Core Task: Aerospace (i3) =========================
- name: Add nikitabobko tap
  community.general.homebrew_tap:
    name: nikitabobko/tap
    state: present

- name: Install Aerospace window manager
  community.general.homebrew_cask:
    name: aerospace
    state: present

# =========================== Core Task: Dotfiles =========================
- name: Copy dotfiles
  copy:
    src: "../dotfiles/"
    dest: "{{ ansible_env.HOME }}"
    owner: "{{ ansible_env.USER }}"
    mode: "0755"
  tags:
    - update-dotfiles

