- name: Clone tomato-frontend-2.0 repository
  git:
    repo: 'git@github.com:tomatoai-dev/tomato-frontend-2.0.git'
    dest: "{{ ansible_env.HOME }}/projects/front"
    version: dev
    accept_hostkey: yes
  environment:
    GIT_SSH_COMMAND: "ssh -vvv"
  register: git_clone_result
  tags: tomato

- name: Clone private Gist for .env file
  git:
    repo: 'git@gist.github.com:d72a1ba1da432efcbe5d6bc522a5bbde.git'
    dest: "{{ ansible_env.HOME }}/projects/front/gist_env"
    version: main
    accept_hostkey: yes
  environment:
    GIT_SSH_COMMAND: "ssh -vvv"
  register: gist_clone_result
  tags: tomato

- name: Copy .env file from cloned Gist
  command: cp gist_env/.env .env
  args:
    chdir: "{{ ansible_env.HOME }}/projects/front"
  tags: tomato

- name: Remove Gist directory
  file:
    path: "{{ ansible_env.HOME }}/projects/front/gist_env"
    state: absent
  tags: tomato

- name: Checkout staging branch
  command: git checkout staging
  args:
    chdir: "{{ ansible_env.HOME }}/projects/front"
  tags: tomato

- name: Pull latest changes from staging
  command: git pull origin staging
  args:
    chdir: "{{ ansible_env.HOME }}/projects/front"
  tags: tomato

- name: Run npm install in the front directory
  command: npm install
  args:
    chdir: "{{ ansible_env.HOME }}/projects/front"
  tags: tomato
